### PR TITLE
Fix a typo

### PR DESCRIPTION
**Pull request by 733amir**
I think you meant `CanGetID`. Am I right?

### CODE REVIEW

**Comment by akutz** [comment]
I know what I meant! How dare you presume to...

(Yeah, totally a typo 😃 )

Thanks for the fix!

**Comment by 733amir** [comment]
Phew! You got me there for a second. 😂

**Comment by akutz** [comment]
Ha! Sorry 😄 I sometimes forget that people are not actually able to hear my voice via text.  Thank you again for the watchful eye!

**Comment by 733amir** [comment]
That's ok :)
Thank you for the informative repository.

**Comment by akutz** [comment]
You are quite welcome. I never suspected it would end up so popular. Honestly, it is kind of stressful. I want to make sure I am not leading anyone astray with incorrect information!

**Pull request merged**
